### ISSUE TITLE
Exclude when suggest is visible & when in snippet mode

### ISSUE THREAD

**Issue by usernamehw** [Gruntfuggly/ubertab#1]
Currently it overwrites <kbd>Tab</kbd> completions.

```json
"when": "... && !inSnippetMode && !suggestWidgetVisible"
```

**Comment by Gruntfuggly** [comment]
Good spot. I'll update it.

This is the first bit of feedback that anybody else is even using it :smile: Thanks!

**Comment by usernamehw** [comment]
Damn, it also conflicts for me with `"editor.tabCompletion": "onlySnippets",`. Gonna need to write an extension to overwrite <kbd>Tab</kbd> first and check if it matches snippet...

Do you use this extension yourself? It could probably be more useful with subword navigation instead of current one.

Also, have you thought of trying to get TM scope of items to use existing parser (to get out of quotes, blocks)? Not 100% sure if it's possible though: https://github.com/Microsoft/vscode/issues/580

**Comment by Gruntfuggly** [comment]
I use it myself sometimes - depending what I'm working on.

I'm quite happy to pull in any enhancements you want to make...

**Comment by usernamehw** [comment]
Probably not this week. I'm going to create issues to not forget about it.

**Comment by usernamehw** [comment]
Actually, removing 2 more contexts would be nice:

```json
"when": "... !editorHasMultipleSelections && !editorHasSelection"
```

**Comment by Gruntfuggly** [comment]
Just uploaded a version with the contexts removed - sorry for the wait!

**Comment by usernamehw** [comment]
It's fine. I was struggling with the snippets and eventually rebound snippet accept to <kbd>spacebar</kbd>.

Just tested the contexts and `!editorHasMultipleSelections` is redundant since `!editorHasSelection` should be true for multiple selections.
