### ISSUE TITLE
[FR] Setting: Use only ubertab - disable indent

### ISSUE THREAD

**Issue by usernamehw** [Gruntfuggly/ubertab#2]
Exactly what the title says: make an option to always tab around (if only 1 cursor and it's an empty selection).
```json
"tabstop.unlimited": false,
```

**Comment by Gruntfuggly** [comment]
Added an option: `ubertab.shouldIndent` which disables indenting if set to false.

**Comment by usernamehw** [comment]
Seems to be working 👍 

This `"true"` should probably be `true`.

https://github.com/Gruntfuggly/ubertab/blob/645001fe6e53dd8c877bab764fa2a60cae750c1a/package.json#L56-L58

**Comment by Gruntfuggly** [comment]
You're right.
