### ISSUE TITLE
[FR] Specify chars on which it should stop

### ISSUE THREAD

**Issue by usernamehw** [Gruntfuggly/ubertab#3]
An option to add tab stop symbols (maybe per language):

```json
"ubertab.tabstopSymbols": [".", "(", ")"],
```

Regex support would be sick, but not sure about performace.

**Comment by Gruntfuggly** [comment]
Been thinking about this - for non-paired symbols, what would you want to happen?

Currently, when tabbing forwards, it looks backwards for one of `{`,`(`,`[` or `<` and whichever one it finds first, it then looks for the matching one forwards. 

If none of the above characters are found, it will move to the next space, so I could look for the next space or other configured characters?

**Comment by usernamehw** [comment]
I don't really know... Let it bet as it is for now.
